### PR TITLE
Updated based on feedback

### PR DESCRIPTION
**Pull request by mattbriggs**
Thanks for your feedback. I didn't _get_ a few of the aspects of the context manager and updating it based on your back allowed me to see how __enter__ and __exit__ are interacting. I'm still a little unsure of the parameters in __exit__ (type, value, traceback) but the overall operation and how to wire up a class-based context manager make sense to me now. Thanks! (I added the __init__ when trying to figure out where I was going wrong...)

### CODE REVIEW

**Comment by mattbriggs** [comment]
I am adding the mailroom project. I plan to add the logging exercise to this version of it when I finish it. I have to rebuild my test version as well. I am going to use this mailroom project from now on. I also have to revisit how to create a package. It isn't really making sense to me.

**Comment by PythonCHB** [comment]
well,  the parameters in `exit(type, value, traceback)`  are about handling the Exceptions that may have been raised. if you don't need to do that, then you can pretty much ignore it :-)

**Comment by PythonCHB** [comment]
And do make it a proper package -- it make it a lot easier to work on.

**Comment by PythonCHB** [comment]
A lot left over from previous PRs -- sorry I didn't get them all merged.

But what would you like reviewed now?

**Comment by PythonCHB** [comment]
I'm merging all this to get it in, and I think you said you didn't need any review.

But do let me know if you have any questions.

-CHB

**Pull request merged**
